### ISSUE TITLE
Require requirements.txt for running this project

### ISSUE THREAD

**Issue by nosherwanijaz** [preddy5/segnet#17]
I'm trying to run SegNet however, I'm seeing a lot of errors in the import statements. This is due to the fact that I'm using updated versions of most packages required.

Can you please provide the requirements.txt file containing the versions of packages that you guys used at the time of implementation. Also, can you please tell me what version of python did you guys use to implement this?

Thanks.

**Comment by preddy5** [comment]
Hey @nosherwanijaz the project is quite old, I dont have access to the environment I used for the :/ sorry about that.
